# Common configurations
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api

spring:
  # Database configuration
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000

  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

  # AI configuration
  ai:
    vectorstore:
      pgvector:
        initialize-schema: true
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
    openai:
      api-key: ${OPENAI_API_KEY}
      embedding:
        options:
          model: 'text-embedding-3-small'

  # Multipart file configuration
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      enabled: true

  # AWS configuration
  cloud:
    aws:
      region:
        static: ${AWS_REGION:ap-south-1}
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}

jwt:
  secretKey: ${JWT_SECRET_KEY}

# Application-specific configuration
paperlink:
  s3:
    bucket-name: ${S3_BUCKET_NAME:paperaitest}
  ai:
    system-prompt: "You are a helpful assistant for PaperLink. Use the provided documents to answer questions accurately."

springdoc:
  packages-to-scan: com.paperlink.server
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
  paths-to-match: /v1/**

# Logging configuration
logging:
  level:
    root: ${LOG_LEVEL:INFO}
    org.springdoc: ${DOC_LOG_LEVEL:INFO}
    com.paperlink: ${APP_LOG_LEVEL:INFO}
    org.springframework.ai: ${AI_LOG_LEVEL:INFO}
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"